// Requires:
//   GOOGLE_CLIENT_ID      — already used for sign-in
//   GOOGLE_CLIENT_SECRET  — add to .env.local
//   NEXT_PUBLIC_BASE_URL  — e.g. https://danilkrava.fit (add to .env.local)

import { OAuth2Client } from "google-auth-library";
import { ObjectId } from "mongodb";
import { getDb } from "./mongodb";

// calendar scope required to create/manage calendars; includes calendar.events
const CALENDAR_SCOPE = "https://www.googleapis.com/auth/calendar";
const CALENDARS_API = "https://www.googleapis.com/calendar/v3/calendars";
const CALENDAR_LIST_API = "https://www.googleapis.com/calendar/v3/users/me/calendarList";

const eventsApi = (calendarId: string) =>
  `${CALENDARS_API}/${encodeURIComponent(calendarId)}/events`;

export function createCalendarOAuthClient(): OAuth2Client {
  return new OAuth2Client({
    clientId: process.env.GOOGLE_CLIENT_ID,
    clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    redirectUri: `${process.env.NEXT_PUBLIC_BASE_URL}/api/calendar/callback`,
  });
}

export function getCalendarAuthUrl(nonce: string): string {
  const client = createCalendarOAuthClient();
  return client.generateAuthUrl({
    access_type: "offline",
    scope: [CALENDAR_SCOPE],
    state: nonce,
    prompt: "consent", // always returns refresh_token
  });
}

export async function exchangeCalendarCode(code: string) {
  const client = createCalendarOAuthClient();
  const { tokens } = await client.getToken(code);
  return tokens;
}

export async function storeCalendarTokens(
  userId: string,
  tokens: { access_token?: string | null; refresh_token?: string | null; expiry_date?: number | null; scope?: string | null }
) {
  const db = await getDb();
  await db.collection("Users").updateOne(
    { _id: new ObjectId(userId) },
    {
      $set: {
        googleCalendarTokens: {
          accessToken: tokens.access_token ?? null,
          refreshToken: tokens.refresh_token ?? null,
          expiryDate: tokens.expiry_date ?? null,
          scope: tokens.scope ?? CALENDAR_SCOPE,
        },
      },
    }
  );
}

export async function isCalendarConnected(userId: string): Promise<boolean> {
  const db = await getDb();
  const user = await db.collection("Users").findOne(
    { _id: new ObjectId(userId) },
    { projection: { "googleCalendarTokens.refreshToken": 1, "googleCalendarTokens.scope": 1 } }
  );
  if (!user?.googleCalendarTokens?.refreshToken) return false;
  // Require the full calendar scope (not just calendar.events)
  const scope: string = user.googleCalendarTokens.scope ?? "";
  return scope.includes("https://www.googleapis.com/auth/calendar");
}

/** Returns a fresh access token, auto-refreshing via stored refresh_token. */
export async function getCalendarAccessToken(userId: string): Promise<string> {
  const db = await getDb();
  const user = await db.collection("Users").findOne(
    { _id: new ObjectId(userId) },
    { projection: { googleCalendarTokens: 1 } }
  );

  if (!user?.googleCalendarTokens?.refreshToken) {
    throw new Error("Google Calendar is not connected.");
  }

  const client = createCalendarOAuthClient();
  client.setCredentials({
    refresh_token: user.googleCalendarTokens.refreshToken,
    access_token: user.googleCalendarTokens.accessToken,
    expiry_date: user.googleCalendarTokens.expiryDate,
  });

  const { token } = await client.getAccessToken();
  if (!token) throw new Error("Failed to obtain access token.");

  // Persist refreshed access token
  if (token !== user.googleCalendarTokens.accessToken) {
    await db.collection("Users").updateOne(
      { _id: new ObjectId(userId) },
      { $set: { "googleCalendarTokens.accessToken": token } }
    );
  }

  return token;
}

/** Returns the ID of the user's "Training Program" Google Calendar, creating it if needed. */
export async function getOrCreateTrainingCalendar(userId: string): Promise<string> {
  const db = await getDb();
  const user = await db.collection("Users").findOne(
    { _id: new ObjectId(userId) },
    { projection: { trainingCalendarId: 1 } }
  );

  if (user?.trainingCalendarId) {
    return user.trainingCalendarId as string;
  }

  const token = await getCalendarAccessToken(userId);

  // Create the calendar
  const createRes = await fetch(CALENDARS_API, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      summary: "Training Program",
      description: "Workouts generated by Training Program Generator — danilkrava.fit",
    }),
  });

  if (!createRes.ok) {
    const err = await createRes.json().catch(() => ({})) as { error?: { message?: string } };
    throw new Error(err.error?.message ?? `Calendar creation failed: ${createRes.status}`);
  }

  const calendar = await createRes.json() as { id: string };

  // Set calendar color to yellow (cosmetic, ignore failures)
  await fetch(`${CALENDAR_LIST_API}/${encodeURIComponent(calendar.id)}`, {
    method: "PATCH",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ backgroundColor: "#EAB308", foregroundColor: "#000000" }),
  }).catch(() => { /* non-fatal */ });

  await db.collection("Users").updateOne(
    { _id: new ObjectId(userId) },
    { $set: { trainingCalendarId: calendar.id } }
  );

  return calendar.id;
}

export interface CalendarEventInput {
  summary: string;
  description?: string;
  start: { dateTime: string; timeZone: string };
  end: { dateTime: string; timeZone: string };
  colorId?: string;
}

export async function createCalendarEvent(
  userId: string,
  event: CalendarEventInput
): Promise<{ id: string; htmlLink: string }> {
  const [token, calendarId] = await Promise.all([
    getCalendarAccessToken(userId),
    getOrCreateTrainingCalendar(userId),
  ]);
  const res = await fetch(eventsApi(calendarId), {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(event),
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({})) as { error?: { message?: string } };
    throw new Error(err.error?.message ?? `Calendar API ${res.status}`);
  }
  return res.json() as Promise<{ id: string; htmlLink: string }>;
}

export async function updateCalendarEvent(
  userId: string,
  eventId: string,
  patch: Partial<CalendarEventInput>
): Promise<{ id: string; htmlLink: string }> {
  const [token, calendarId] = await Promise.all([
    getCalendarAccessToken(userId),
    getOrCreateTrainingCalendar(userId),
  ]);
  const res = await fetch(`${eventsApi(calendarId)}/${encodeURIComponent(eventId)}`, {
    method: "PATCH",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(patch),
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({})) as { error?: { message?: string } };
    throw new Error(err.error?.message ?? `Calendar API ${res.status}`);
  }
  return res.json() as Promise<{ id: string; htmlLink: string }>;
}

export async function deleteCalendarEvent(
  userId: string,
  eventId: string
): Promise<void> {
  const [token, calendarId] = await Promise.all([
    getCalendarAccessToken(userId),
    getOrCreateTrainingCalendar(userId),
  ]);
  const res = await fetch(`${eventsApi(calendarId)}/${encodeURIComponent(eventId)}`, {
    method: "DELETE",
    headers: { Authorization: `Bearer ${token}` },
  });
  // 410 = already deleted, treat as success
  if (!res.ok && res.status !== 410) {
    throw new Error(`Calendar API ${res.status}`);
  }
}

export interface CalendarEventItem {
  id: string;
  summary: string;
  start: { dateTime?: string; date?: string };
  end: { dateTime?: string; date?: string };
}

export async function listCalendarEvents(
  userId: string,
  timeMin: string,
  timeMax: string
): Promise<CalendarEventItem[]> {
  const [token, calendarId] = await Promise.all([
    getCalendarAccessToken(userId),
    getOrCreateTrainingCalendar(userId),
  ]);
  const params = new URLSearchParams({
    timeMin,
    timeMax,
    singleEvents: "true",
    orderBy: "startTime",
    maxResults: "250",
  });
  const res = await fetch(`${eventsApi(calendarId)}?${params}`, {
    headers: { Authorization: `Bearer ${token}` },
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({})) as { error?: { message?: string } };
    throw new Error(err.error?.message ?? `Calendar API ${res.status}`);
  }
  const data = await res.json() as { items: CalendarEventItem[] };
  return data.items ?? [];
}
